version: '3'
services:
  storage:
    image: busybox
    volumes:
      - /var/lib/mysql
    container_name: app_name-storage
  mysql:
    image: mysql:5.6
    volumes:
      - storage
    ports:
      - "3306:3306"
    container_name: app_name-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    container_name: app_name-db
    volumes:
      - storage
  web:
    build: .
    volumes:
      - .:/var/opt/app
    environment:
      - "TZ=Japan"
      - "DB_HOST=app_name-db"
    links:
      - mysql:mysql
    ports:
      - "4000:4000"
    container_name: app_name-web
